import { describe, it, expect } from "vitest";
import { buildNotebook } from "./notebook";

describe("buildNotebook (Colab export)", () => {
  const meta = { title: "Test Tutorial", description: "Desc", provider: "poe", model: "gpt-oss-20b" };
  const steps = [
    { step_order: 1, title: "Hello", content: "Say hello", code_template: "Write a short greeting." },
    { step_order: 2, title: "JSON", content: "Return JSON", code_template: "Respond with a JSON object with name and version." },
  ];
  const assessments = [
    { step_order: 1, question: "2+2?", options: ["3", "4"], correct_index: 1, explanation: "2+2=4" },
  ];

  it("includes intro, setup, env, and smoke test cells", () => {
    const nb = buildNotebook(meta, steps, assessments);
    expect(nb.cells.length).toBeGreaterThan(6);

    // First cell is attribution comment
    const attribution = nb.cells[0];
    expect(attribution.cell_type).toBe("markdown");
    expect(attribution.source.join("")).toContain("Generated by ALAIN");

    // Second cell is the intro
    const intro = nb.cells[1];
    expect(intro.cell_type).toBe("markdown");
    expect(intro.source.join(""))
      .toContain("Test Tutorial");

    // There should be an install cell that installs from requirements.txt
    const pipCell = nb.cells.find(c => c.cell_type === 'code' && c.source.join("").includes("pip install -q -r requirements.txt"));
    expect(pipCell).toBeTruthy();

    // Environment cell should set OPENAI_BASE_URL and OPENAI_API_KEY
    const envCell = nb.cells.find(c => c.cell_type === 'code' && c.source.join("").includes("OPENAI_BASE_URL"));
    expect(envCell).toBeTruthy();
    expect(envCell!.source.join("")).toContain("OPENAI_API_KEY");

    // There should be a smoke test cell invoking chat.completions
    const smoke = nb.cells.find(c => c.cell_type === 'code' && c.source.join("").includes("client.chat.completions.create"));
    expect(smoke).toBeTruthy();
  });

  it("renders step prompts into runnable code cells", () => {
    const nb = buildNotebook(meta, steps, assessments);
    const codeCells = nb.cells.filter(c => c.cell_type === "code");
    const body = codeCells.map(c => c.source.join("")).join("\n---\n");
    // Accept triple-single or triple-double quotes for PROMPT string.
    expect(body.match(/PROMPT\s*=\s*("""|''')/)).toBeTruthy();
    expect(body).toContain("Write a short greeting.");
    expect(body).toContain("client.chat.completions.create");
  });

  it("includes MCQ cells with grading logic", () => {
    const nb = buildNotebook(meta, steps, assessments);
    const mcqCell = nb.cells.find(c => c.cell_type === "code" && c.source.join("").includes("Assessment for Step 1"));
    expect(mcqCell).toBeTruthy();
    const src = mcqCell!.source.join("");
    expect(src).toContain("question = ");
    expect(src).toContain("options = ");
    expect(src).toContain("correct_index = 1");
    expect(src).toContain("choice = 0");
  });
});
