export type NBCell = {
  cell_type: "markdown" | "code";
  metadata: Record<string, any>;
  source: string[];
  outputs?: any[];
  execution_count?: number | null;
};

export type Notebook = {
  cells: NBCell[];
  metadata: Record<string, any>;
  nbformat: number;
  nbformat_minor: number;
};

export function buildNotebook(
  meta: { title: string; description: string; provider: string; model: string },
  steps: Array<{ step_order: number; title: string; content: string; code_template: string | null; model_params?: any }>,
  assessments: Array<{ step_order: number; question: string; options: string[]; correct_index: number; explanation: string | null }>
): Notebook {
  const cells: NBCell[] = [];

  // 1) Intro
  cells.push({
    cell_type: "markdown",
    metadata: {},
    source: [
      `# ${meta.title}\n`,
      `\n`,
      `${meta.description}\n`,
      `\n`,
      `> Provider: \`${meta.provider}\`  •  Model: \`${meta.model}\`\n`,
      `\n`,
      `This notebook was generated by ALAIN. It calls AI models via OpenAI-compatible APIs (no arbitrary code).\n`
    ],
  });

  // 2) Setup: install deps
  cells.push({
    cell_type: "code",
    metadata: {},
    source: [
      "# Install client SDKs (if missing)\n",
      "!pip -q install openai>=1.34.0\n",
    ],
    outputs: [],
    execution_count: null,
  });

  // 3) Provider env/config
  const providerBase = meta.provider === 'poe' ? 'https://api.poe.com/v1' : 'YOUR_OPENAI_BASE_URL';
  const envSource = [
    "# Configure OpenAI-compatible client\n",
    "import os\n",
    `PROVIDER = "${meta.provider}"  # "poe" or "openai-compatible"\n`,
    `os.environ.setdefault("OPENAI_BASE_URL", "${providerBase}")\n`,
    `# Set your API key. For Poe, set POE_API_KEY in the Colab environment or paste below.\n`,
    `os.environ.setdefault("OPENAI_API_KEY", os.getenv("POE_API_KEY") or "YOUR_API_KEY_HERE")\n`,
  ];
  cells.push({ cell_type: "code", metadata: {}, source: envSource, outputs: [], execution_count: null });

  // 4) Quick smoke test
  cells.push({
    cell_type: "code",
    metadata: {},
    source: [
      "# Quick smoke test\n",
      "from openai import OpenAI\n",
      "import os\n",
      "base = os.environ.get('OPENAI_BASE_URL')\n",
      "key = os.environ.get('OPENAI_API_KEY')\n",
      "assert base and key, 'Please set OPENAI_BASE_URL and OPENAI_API_KEY env vars'\n",
      "client = OpenAI(base_url=base, api_key=key)\n",
      `resp = client.chat.completions.create(model="${meta.model}", messages=[{"role":"user","content":"Hello from ALAIN"}], max_tokens=32)\n`,
      "print(resp.choices[0].message.content)\n",
    ],
    outputs: [],
    execution_count: null,
  });

  // Utility to find assessments per step
  function listAssessments(step_order: number) {
    return assessments.filter(a => a.step_order === step_order);
  }

  // 5) Lesson steps
  for (const s of steps) {
    // Step markdown
    cells.push({
      cell_type: "markdown",
      metadata: {},
      source: [`## Step ${s.step_order}: ${s.title}\n`, `\n`, `${s.content}\n`],
    });

    // Step execution scaffold (uses global client from smoke test)
    const prompt = (s.code_template || '').endsWith("\n") ? (s.code_template || '') : (s.code_template || '') + "\n";
    const t = s.model_params?.temperature ?? 0.7;
    const safePrompt = prompt.replace(/'''/g, "\\'\\'\\'");
    const stepSource = [
      "# Run the step prompt using the configured provider\n",
      `PROMPT = '''${safePrompt}'''\n`,
      "from openai import OpenAI\n",
      "import os\n",
      "client = OpenAI(base_url=os.environ['OPENAI_BASE_URL'], api_key=os.environ['OPENAI_API_KEY'])\n",
      `resp = client.chat.completions.create(model="${meta.model}", messages=[{"role":"user","content":PROMPT}], temperature=${t}, max_tokens=400)\n`,
      "print(resp.choices[0].message.content)\n",
    ];
    cells.push({ cell_type: "code", metadata: {}, source: stepSource, outputs: [], execution_count: null });

    // MCQs (if any)
    const qs = listAssessments(s.step_order);
    for (const a of qs) {
      const mcq = [
        `# Assessment for Step ${s.step_order}\n`,
        `question = ${JSON.stringify(a.question)}\n`,
        `options = ${JSON.stringify(a.options)}\n`,
        `correct_index = ${a.correct_index}\n`,
        `print('Q:', question)\n`,
        `for i, o in enumerate(options):\n    print(f"{i}. {o}")\n`,
        `choice = 0  # <- change this to your answer index\n`,
        `print('Correct!' if choice == correct_index else 'Incorrect')\n`,
        `${a.explanation ? `print('Explanation:', ${JSON.stringify(a.explanation)})\n` : ''}`,
      ];
      cells.push({ cell_type: "code", metadata: {}, source: mcq, outputs: [], execution_count: null });
    }
  }

  return {
    cells,
    metadata: {
      kernelspec: { name: "python3", language: "python", display_name: "Python 3" },
      language_info: { name: "python" },
    },
    nbformat: 4,
    nbformat_minor: 5,
  };
}
