name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies (root workspaces)
        working-directory: alain-ai-learning-platform
        run: npm ci

      - name: Backend tests (pure)
        working-directory: alain-ai-learning-platform
        run: npm run test:pure

      - name: Build web
        working-directory: alain-ai-learning-platform/web
        env:
          NEXT_TELEMETRY_DISABLED: '1'
        run: |
          npm run build

